[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/mail"
  to = "/.netlify/functions/sendEmail"
  status = 200

[[redirects]]
  from = "/api/text"
  to = "/.netlify/functions/sendText"
  status = 200